import logging
import os

from github import Auth, Github

from src.state import PRReviewState
from src.github_app_auth import get_github_client

logger = logging.getLogger(__name__)


def post_github_comment_node(state: PRReviewState) -> dict:
    """
    Posts the aggregated review report as a comment on the GitHub PR thread.
    """
    logger.info(f"Publishing review to {state['repo_name']} PR #{state['pr_number']}...")

    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN environment variable is not set.")

    # g    = Github(auth=Auth.Token(token))
    g = get_github_client(state["repo_name"])
    repo = g.get_repo(state["repo_name"])
    pr   = repo.get_pull(state["pr_number"])

    body = (
        "## 🤖 Automated Multi-Agent Code Review\n\n"
        f"{state['final_report']}\n\n"
        "---\n"
        "_Generated by PR Reviewer · Powered by LangGraph_"
    )

    # pr.create_issue_comment(body)
    pr.create_review(
        body=body,
        event="REQUEST_CHANGES" if state.get("highest_severity") == "CRITICAL" else "COMMENT"
    )
    logger.info(f"Successfully posted comment to PR #{state['pr_number']}.")

    return {}
